{% set name = "chemdyg" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/E3SM-Project/ChemDyg/archive/refs/tags/v{{ version }}.tar.gz
  sha256: a775f554f825840547870b482d4c6bda33225c07543153f11a4a13a18a1ff565

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - cartopy
    - matplotlib-base
    - netcdf4
    - numpy
    - pandas
    - scipy
    - xarray
    - zppy >=2.2.0

test:
  imports:
    - chemdyg
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/E3SM-Project/ChemDyg
  summary: Chemistry Diagnostics Package
  description: |
    E3SM chemistry diagnostic package (ChemDyg) is designed for
    E3SM chemistry development, including plots and tables for model-to-model and model-to-observation comparison.

  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://github.com/E3SM-Project/ChemDyg
  dev_url: https://github.com/E3SM-Project/ChemDyg

extra:
  recipe-maintainers:
    - xylar
    - hsiangheleellnl
    - tangq
