{% set name = "chemdyg" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/E3SM-Project/ChemDyg/archive/refs/tags/v{{ version }}.tar.gz
  sha256: aa7519938fd43e5d44d1b5584b81861b858e74454055de32dd7e30d17d1e3744

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - cartopy
    - matplotlib-base
    - netcdf4
    - numpy
    - pandas
    - scipy
    - xarray
    - zppy >=3.0.0
test:
  imports:
    - chemdyg
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/E3SM-Project/ChemDyg
  summary: Chemistry Diagnostics Package
  description: |
    E3SM chemistry diagnostic package (ChemDyg) is designed for
    E3SM chemistry development, including plots and tables for model-to-model and model-to-observation comparison.

  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://github.com/E3SM-Project/ChemDyg
  dev_url: https://github.com/E3SM-Project/ChemDyg

extra:
  recipe-maintainers:
    - xylar
    - hsiangheleellnl
    - tangq
